[unstable]
unstable-options = true
config-include = true
panic-abort-tests = true
mtime-on-use = true
avoid-dev-deps = true
profile-rustflags = true


[env]
MIRIFLAGS = "-Zmiri-symbolic-alignment-check -Zmiri-track-alloc-accesses -Zmiri-unique-is-unique -Zmiri-tree-borrows -Zmiri-strict-provenance"
