api:
  - changed-files:
      - any:
          - "api/**"
          - "components/**"

pre-built bindings:
  - changed-files:
      - any:
          - "api/gen/*"

cargo:
  - changed-files:
      - any:
          - "cargo/**"

bindgen:
  - changed-files:
      - any:
          - "support/bindgen/**"
          - "support/bindgen-cfg/**"

docs:
  - changed-files:
      - any:
          - "**/*.md"
          - "**/*.txt"
