# doc: https://embarkstudios.github.io/cargo-deny/checks/sources/cfg.html

[graph]
targets = [
	"thumbv7em-none-eabihf",
	"aarch64-apple-darwin",
	"x86_64-apple-darwin",
	"aarch64-unknown-linux-gnu",
	"x86_64-unknown-linux-gnu",
	"x86_64-unknown-linux-musl",
	"x86_64-pc-windows-msvc",
]
all-features = false
no-default-features = false
features = []


[advisories]
# db-path = "~/.cargo/advisory-dbs"
# db-urls = ["https://github.com/rustsec/advisory-db"]
ignore = [
	{ id = "RUSTSEC-2024-0436", reason = "Unmaintained - it's ok, also there is no available alternative." },
]


[licenses]
confidence-threshold = 0.8
allow = [
	"Unlicense",
	"Apache-2.0",
	"Apache-2.0 WITH LLVM-exception",
	"MIT",
	"MPL-2.0",
	"BSD-3-Clause",
	"ISC",
	"Unicode-3.0",
]

[[licenses.exceptions]]
allow = ["Zlib"]
crate = "const_format"

[[licenses.exceptions]]
allow = ["Zlib"]
crate = "const_format_proc_macros"

[[licenses.exceptions]]
allow = ["BSL-1.0"]
crate = "lockfree-object-pool"

[licenses.private]
ignore = true
registries = []


[bans]
multiple-versions = "warn"           # TODO: allow
wildcards = "warn"
highlight = "simplest-path"
workspace-default-features = "allow"
external-default-features = "allow"
allow = []
deny = []
skip = []
skip-tree = []


[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []

[sources.allow-org]
github = []
gitlab = []
bitbucket = []
