scripts:
  - &rustup
    name: Rustup
    script: >-
      curl https://sh.rustup.rs -sSf | sh -s -- -y --profile minimal
      --default-toolchain nightly
      -c rustfmt
      -c rust-src
      -t thumbv7em-none-eabihf

  - &install_sdk
    name: SDK
    script: |
      URL="https://download.panic.com/playdate_sdk/PlaydateSDK-${SDK_VERSION?}.zip"
      curl -L -sS --show-error --fail "${URL?}" -o sdk.zip
      unzip sdk.zip
      sudo installer -store -pkg "PlaydateSDK.pkg" -target /

      echo "CFG: $(cat ~/.Playdate/config)"
      export PLAYDATE_SDK_PATH="$(grep -E '^\s*SDKRoot' ~/.Playdate/config | head -n 1 | awk '{print $2}')"
      echo "SDK root: $PLAYDATE_SDK_PATH"
      echo "SDK version=$(cat $PLAYDATE_SDK_PATH/VERSION.txt)"
      echo "PLAYDATE_SDK_PATH=$PLAYDATE_SDK_PATH" >> $CM_ENV

      # clean
      rm -rf sdk.zip
      rm -rf PlaydateSDK.pkg
      rm -rf __MACOSX

workflows:
  test:
    name: Tests / Execution
    max_build_duration: 20
    instance_type: mac_mini_m1
    environment:
      groups:
        - github_credentials
      vars:
        CARGO_INCREMENTAL: 1
        CARGO_NET_RETRY: 10
        RUSTUP_MAX_RETRIES: 10
        CARGO_TERM_COLOR: always
        CARGO_TERM_PROGRESS_WHEN: never
        RUST_LOG: trace
        CARGO_PLAYDATE_LOG: trace
        SDK_VERSION: latest
        PLAYDATE_SDK_PATH: ~/Developer/PlaydateSDK
      xcode: latest

    cache:
      cache_paths:
        - ~/.rustup
        - ~/.cargo
        - ./target

    triggering:
      events:
        - pull_request
      cancel_previous_builds: false
    # when:
    #   condition: not event.pull_request.draft

    scripts:
      - *rustup
      - *install_sdk

      - name: Execution
        script: |
          source "$HOME/.cargo/env"
          RUSTFLAGS="--cfg exec_tests" cargo test -p=cargo-playdate run -- --nocapture
          sudo killall "Playdate Simulator"

      - name: Reset manifests
        script: git checkout HEAD -- ./Cargo.*

      - name: Clean
        script: |
          rm -rf ./target/tmp || true
          rm -rf ./target/playdate || true
