use crate::ffi::PlaydateLua;


pub static LUA: PlaydateLua = PlaydateLua { addFunction: None,
                                            registerClass: None,
                                            pushFunction: None,
                                            indexMetatable: None,
                                            stop: None,
                                            start: None,
                                            getArgCount: None,
                                            getArgType: None,
                                            argIsNil: None,
                                            getArgBool: None,
                                            getArgInt: None,
                                            getArgFloat: None,
                                            getArgString: None,
                                            getArgBytes: None,
                                            getArgObject: None,
                                            getBitmap: None,
                                            getSprite: None,
                                            pushNil: None,
                                            pushBool: None,
                                            pushInt: None,
                                            pushFloat: None,
                                            pushString: None,
                                            pushBytes: None,
                                            pushBitmap: None,
                                            pushSprite: None,
                                            pushObject: None,
                                            retainObject: None,
                                            releaseObject: None,
                                            setUserValue: None,
                                            getUserValue: None,
                                            callFunction_deprecated: None,
                                            callFunction: None };
