use crate::ffi::PlaydateSound;

pub static SOUND: PlaydateSound = PlaydateSound { channel: core::ptr::null(),
                                                  fileplayer: core::ptr::null(),
                                                  sample: core::ptr::null(),
                                                  sampleplayer: core::ptr::null(),
                                                  synth: core::ptr::null(),
                                                  sequence: core::ptr::null(),
                                                  effect: core::ptr::null(),
                                                  lfo: core::ptr::null(),
                                                  envelope: core::ptr::null(),
                                                  source: core::ptr::null(),
                                                  controlsignal: core::ptr::null(),
                                                  track: core::ptr::null(),
                                                  instrument: core::ptr::null(),
                                                  getCurrentTime: None,
                                                  addSource: None,
                                                  getDefaultChannel: None,
                                                  addChannel: None,
                                                  removeChannel: None,
                                                  setMicCallback: None,
                                                  getHeadphoneState: None,
                                                  setOutputsActive: None,
                                                  removeSource: None,
                                                  signal: core::ptr::null(),
                                                  getError: None };
